spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 130720MB
      max-request-size: 130720MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//52.87.1.4:1521/dbpres
    username: DEVYHS
    password: 'Ax440tzBkV64'
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2

  jackson:
    mapper:
      default_view_inclusion: true
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
serverExternal:
  yopter: http://localhost:9998
