
---
spring:
  profiles: cloud

server:
  port: 9997
  
zuul:
  host:
    max-total-connections: 10000
    max-per-route-connections: 1000
  sensitive-headers: Cookie,Set-Cookie

hystrix:
  threadpool:
    default: 
      coreSize: 9000
      maximumSize: 1000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation: 
          strategy: THREAD 
          thread: 
            timeoutInMilliseconds: 80000
 
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  client:
    registerWithEureka: true
    
---
spring:
  profiles: pre

server:
  port: 9997

zuul:
  health:
    enabled: true
  sensitive-headers: Cookie,Set-Cookie
hystrix:
  threadpool:
    default: 
      coreSize: 10000
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 
eureka:
  client:
    registerWithEureka: true
    
---
spring:
  profiles: dev

server:
  port: 9997

zuul:
  sensitive-headers: Cookie,Set-Cookie
hystrix:
  threadpool:
    default: 
      coreSize: 10000
  command:
    default:
      execution:
        timeout:
          enabled: false    
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 

eureka:
   instance:
     preferIpAddress: true
   client:
     serviceUrl:
       defaultZone: http://127.0.0.1:8762/eureka/
       
---
spring:
  profiles: test

server:
  port: 9997
  
zuul:
  health:
    enabled: true
  sensitive-headers: Cookie,Set-Cookie
hystrix:
  threadpool:
    default: 
      coreSize: 5000
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 
eureka:
  client:
    registerWithEureka: true
