spring:
  profiles: pre

server:
  port: 9997

zuul:
  sensitive-headers: Cookie,Set-Cookie
hystrix:
  threadpool:
    default: 
      coreSize: 10000
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000    
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 

eureka:
   instance:
     preferIpAddress: true
   client:
     serviceUrl:
       defaultZone: http://127.0.0.1:8761/eureka/
---
spring:
  profiles: dev

server:
  port: 9997

zuul:
  sensitive-headers: Cookie,Set-Cookie
hystrix:
  threadpool:
    default: 
      coreSize: 10000
  command:
    default:
      execution:
        timeout:
          enabled: false    
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 

eureka:
   instance:
     preferIpAddress: true
   client:
     serviceUrl:
       defaultZone: http://127.0.0.1:8761/eureka/
