spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 130720MB
      max-request-size: 130720MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@//52.87.1.4:1521/dbpres
    username: Dinere
    password: 'YH34tJ'
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2

  jackson:
    mapper:
      default_view_inclusion: true
server:
  port: 9997

zuul:
  sensitive-headers: Cookie,Set-Cookie
hystrix:
  threadpool:
    default:
      coreSize: 10000
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
